server:
  port: 8081
  
spring:
  datasource:
    #url:  jdbc:mysql://localhost:3306/mytest?characterEncoding=utf8&useSSL=true
    url:  jdbc:mysql://mysql57:3306/mysql
    username:  root
    password:  root
    driver-class-name:  com.mysql.jdbc.Driver
  jpa:
     database-platform: org.hibernate.dialect.MySQL5Dialect
     show-sql: true
     hibernate:
       ddl-auto: update
 